### ISSUE TITLE
[Data Augmentation using GAN's] 

### ISSUE THREAD

**Issue by mzmmoazam** [kili-technology/kili-blogger-program#14]
### My resource

**Topic:**
Data Augmentation using GAN's

**Outline:**
- Describe Data Augmentation and GAN's
- Give detailed instructions and code snippets to develop a GAN network using PyTorch
- Provide more resources and references

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
Hello @LaksCastro
Thank you for your interest and your article proposal.
This topic is very interesting. We expect in the long term to develop data augmentation features on the platform but not data generation features. As we don't expect to deal with it on a platform, doing a tutorial or article on it might be a good idea for people wanting to augment their dataset with such a method.

I come back to you after New Year Eve to validate or not such content!
Thank you and best wishes!

**Comment by theodu** [comment]
Hi @mzmmoazam 
We have decided not to tackle data augmentation in a specific article at the time. It will be addressed as a part of #49.
Thus we won't select this article.
Don't hesitate to make other article proposals!
