### ISSUE TITLE
[PyTorch Implementation]: Learning to Track at 100 FPS with Deep Regression Networks

### ISSUE THREAD

**Issue by nrupatunga** [kili-technology/kili-blogger-program#15]
### My resource
The main article covers about
- Conceptual understanding of the GOTURN paper (https://arxiv.org/abs/1604.01802)
- How to generate the data for training using imagenet dataset and visualizing the data after generation
- Training and inference

**Outline:** Understanding Single object tracking using neural network

### My content is

- [ ] Understanding the paper
- [ ] Implementation

**Comment by theodu** [comment]
Hello @nrupatunga 
Thank you for your interest and your content proposal.
We already have an object tracker implemented on the platform doing SOT task. You can have a look at our [documentation](https://cloud.kili-technology.com/docs/video-interfaces/object-detection/#edit-an-object-on-multiple-frames). We use a model much more recent than GOTURN achieving very good performances.

As we already have a tracker on the platform, this article is less relevant for the Kili Community. However, if you have good experience in object model tracking, an article on this topic might interest us a lot!
You could for example write articles on tasks that we don't achieve in the platform such as multiple object tracking etc.

For the next article proposal, please keep the template structure and add a more detailed outline of your content.
Thank you very much and best wishes!
