### ISSUE TITLE
[New article for Kili Blog] The basics of version control with Git and GitHub

### ISSUE THREAD

**Issue by DamianArado** [kili-technology/kili-blogger-program#16]
### My resource

**Topic:** Learn to clone and create version-controlled GitHub repositories using the command line.

**Outline:**
- Git and GitHub
- Using Git at the Command Line
- Creating a GitHub repository

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by pnchinmay** [comment]
I would really like to take up this article, if it's not already taken.
