### ISSUE TITLE
[New article for Kili Blog] Reproducible reports

### ISSUE THREAD

**Issue by DamianArado** [kili-technology/kili-blogger-program#17]
### My resource

**Topic:** How to create data science reports using R Markdown and the knitr package.

**Outline:**
- Reproducible Reports with R Markdown
- R Markdown
- knitr

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
Hello @DamianArado 
Thank you for your interest and your content proposal.
Could you give a more detailed outline and explain how such a reproducible report might help someone wanting to build a dataset for a machine learning task ?

Thank you and best wishes!

**Comment by DamianArado** [comment]
The final product of a data analysis project is often a report. Many scientific publications can be thought of as a final report of data analysis. 

The same is true for a news article based on data, an analysis report for a company, or lecture notes for a class on how to analyze data. The reports are often on paper or they can be PDFs that include textual descriptions of the findings along with some figures and tables resulting from the analysis. 

Now, imagine that after we've finished the analysis and the report, we're told that we were given the wrong dataset, and they send us a new one and we're asked to run the same analysis but with this new dataset. 

Or, what if we realized that a mistake was made and we need to re-examine the code, fix the error, and rerun the analysis? 
Or imagine that someone we're training wants to see the code we used for the report and be able to reproduce the results to learn about the approach. 

Situations like the ones just described are actually quite common for a data scientist. Here, we describe how to generate reproducible reports with RMarkdown and knitr in a way that will greatly help with situations such as the ones I described above. 

The main feature is that code and textual descriptions can be combined into the same document. And the figures and tables produced by the code are automatically added to the document. 😄

**Comment by theodu** [comment]
Hi @DamianArado 
I now see clearer, thank you!
This is interesting but we cannot prioritize this. It is a bit outside our scope and as we are still at the beginning of the blogger program so we cant prioritize such topics.
Thank you and don't hesitate to propose other tutorials or articles!
