### ISSUE TITLE
NVIDIA CUDA WSL2 + Docker Windows

### ISSUE THREAD

**Issue by neomatrixcode** [kili-technology/kili-blogger-program#18]
### My resource
The guide describes the steps to follow to install Docker containers for machine learning and use them with the Windows client, going through the installation and configuration of WSL2, CUDA Toolkit, Nvidia-docker and Docker Windows.

**Topic:**
NVIDIA CUDA in WSL2 + Docker Windows 
**Outline:**

- Requirements
- Step 1: NVIDIA Driver CUDA in WSL
- Step 2: Install WSL2
- Step 3: Update WSL2
- Step 4: Add the NVIDIA Software Repository in WSL2
- Step 5: Install NVIDIA CUDA Toolkit 11 on WSL2
- Step 6: Install Deep Learning Tools on WSL2
- Step 7 (Optional): Install RT Tensioner Tools on WSL2
- Step 8: Run one of the samples
- CUDA + WSL + DOCKER
- Install nvidia-docker2 on WSL
- Start Docker on WSL2
- Connect Docker Windows to WSL2

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hello @neomatrixcode 
Thank you for your article proposal.
However, setting up a workspace as you describe in your outline is not something that interests us on our blog. It should be more data-related.

Thank you for your proposal and best wishes!
