### ISSUE TITLE
[New article for Kili Blog] Jenkins Plugins

### ISSUE THREAD

**Issue by DamianArado** [kili-technology/kili-blogger-program#19]
### My resource

**Topic:** One of the reasons for Jenkins’s popularity as a CI/CD tool is its large plugin ecosystem. This article will give an overview of Jenkins plugins and explain how to manage them.

**Outline:**
- Discuss about Jenkins plugins ecosystem
- Install plugins
- Upgrade plugins
- Uninstall plugins

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
Hello @DamianArado 
Thank you for your interest and your content proposal.
Model deployment is a good topic but it might be interesting in our blog if it is related to the data. 
I invite you to have a look at the article looking for an author :[Create a feedback loop for ML in production](https://github.com/kili-technology/kili-blogger-program/issues/3).

Thank you and best wishes!
