### ISSUE TITLE
Handling gene expression data as tabular with TabNet  

### ISSUE THREAD

**Issue by HiramCillo** [kili-technology/kili-blogger-program#20]
### My resource

This will be a tutorial about **TabNet**. The main task is  multi-class classification, using **gene expression data** to predict cell types.  After that i'm going to get (and plot) the **feature importance** of the top genes.    

**Topic:** Deep Learning, Tabular Data, XAI, Transformers, Bioinformatics

**Outline:** 
- Introduction 
- EDA
- Preprocessing and Quality Control
- Training 
- XAI 
- References

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hi @HiramCillo 
Thank you for your interest and your content proposal.
I think that writing such an article for multi-class classification in bioinformatics is interesting. However Bioinformatic is not a data type currently used by the Kili community. I will get in touch with the team to see if it is relevant to write such an article at that time. 
I will come back after New Year Eve to let you know if we can assign you to this article.

In every case, even if writing an article on bioinformatic multi-class classification is validated on our side, the outline should have some modifications. It would be necessary to integrate the Kili platform in your use case and to have a very data-related approach. You can think about these modifications while I get back to you. Here is the [Kili Documentation](https://cloud.kili-technology.com/docs/introduction/introduction-to-kili-technology.html) if you are not comfortable with our product.

Thank you and best wishes!

**Comment by theodu** [comment]
Hi @HiramCillo 
This article has not been selected for further writing. It doesn't target data annotation and dataset management enough. don't hesitate to propose other articles!
Happy New year
