### ISSUE TITLE
[New Article for Kili Blog] Setting up Deep Learning workstation in Ubuntu 20.04

### ISSUE THREAD

**Issue by pnchinmay** [kili-technology/kili-blogger-program#21]
### My resource
The guide describes the steps to follow to setup Deep Learning workstation in Ubuntu 20.04. The article walks through the installation of GPU drivers, Anaconda, Pycharm for machine learning and use them with the Ubuntu client, going through their installation and configuration of GPU drivers, CUDA Toolkit, CuDNN, Anaconda, Conda env, and Pycharm.

**Topic:** Setting up Deep Learning workstation in Ubuntu 20.04

**Outline:**
- GPU drivers
- CUDA
- CuDNN
- Anaconda
- setting conda env
- PyCharm
- integrating PyCharm with Anaconda
- Tensorflow
- PyTorch

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hello @pnchinmay 
Thank you for your article proposal.
However, setting up a workspace as you describe in your outline is not something that interests us on our blog. it should be more data-related.

Thank you for your proposal and best wishes!
