### ISSUE TITLE
[New Article for Kili Blog] Setting up Terminal workspace that will boost your workflow

### ISSUE THREAD

**Issue by pnchinmay** [kili-technology/kili-blogger-program#22]
### My resource
The guide describes the steps to follow to setup Terminal in Ubuntu 20.04. The article walks through setting up of  zsh shell and its various plugins for machine learning and use them with the Ubuntu client, going through their installation and configuration of .zshrc, aliases, fzf among others.

**Topic:** Setting up Terminal workspace that will boost your workflow

**Outline:**
- zsh installation
- zsh as default shell
- installing fzf 
- integrating fzf in shell using various shell functions
- integrating fzf with git
- installing and configuring OhMyZsh framework for z shell
- configuring the terminal to show various versions right in the prompt
- setting up aliases
- installing powerlevel10k and theming terminal colors 

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hello @pnchinmay 
Thank you for your article proposal.
However, setting up a workspace like you describe in your outline is not something that interests us on our blog. it should be more data-related.

Thank you for your proposal and best wishes!
