### ISSUE TITLE
[New Article for Kili Blog] Managing Dotfiles to simplify setup in next workspace installation

### ISSUE THREAD

**Issue by pnchinmay** [kili-technology/kili-blogger-program#23]
### My resource
This article walks through the introduction of dotfiles and the need to manage those with git. It goes through the installation of git, setting up a git repository, configuring using `--bare` flag and work tree, symlinking and other stuffs that involve in managing dotfiles.

**Topic:** Managing Dotfiles to simplify setup in next workspace installation

**Outline:**
- Installing git
- Setting up a git repository
- Various methods to back up dotfiles
- Copy-paste approach
- Symlinking Approach
- $HOME work tree approach
- Adding existing dotfiles to the new system
- Installing the dotfiles on new setup

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hello @turhancan97
Thank you for your interest and your article proposal.
However, this does not fit in the Kili Scope about managing a dataset for machine learning purposes of what I understand. thus, we won't select this article.

Thank you and best wishes!
