### ISSUE TITLE
[Article Proposal] RDF2Vec: A Gentle Introduction to Create a 2D Feature Matrix from a Knowledge Graph

### ISSUE THREAD

**Issue by rememberYou** [kili-technology/kili-blogger-program#25]
### My resource

This article will start by briefly explaining the importance of the Semantic Web in Machine Learning. Then, this article will include a talk about some fundamental concepts, namely Knowledge Graphs, Word2Vec, and RDF2Vec. Finally, this article will present [pyRDF2Vec](https://github.com/IBCNServices/pyRDF2Vec) with some features and end with a conclusion. 

**NOTE:** probably that I will introduce a tutorial in the future on pyRDF2Vec, where I will redirect to this article for the theoretical background. 

**Topic:** RDF2Vec: A Gentle Introduction to Create a 2D Feature Matrix from a Knowledge Graph 

**Outline:** 
- Introduction
- Knowledge Graph
- Word2Vec
- RDF2Vec
  - Walking Strategies
  - Sampling Strategies
- pyRDF2Vec
- Conclusion

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
Hello @rememberYou 
Thank you for your interest and your content proposal.
This is a very interesting topic but we are currently not working on the RDF side. The community doesn't use it currently so it is not an article that will be interesting on the blog at the time.

Thank you and best wishes!
