### ISSUE TITLE
[Article Proposal] Image Classification with Vision Transformer

### ISSUE THREAD

**Issue by ayyucedemirbas** [kili-technology/kili-blogger-program#27]
### My resource

**Topic:**

Image Classification with Vision Transformer

**Outline:**

In this tutorial, you will learn regression and classification, basics of image classification, data preparation, and image classification with vision transformer. 

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hello @dushyantRathore Hello @dushyantRathore
Thank you for your interest and your article proposal.
This subject is very interesting but it would need to be related to Kili. I think that a lot of people might be interested in importing pre-annotations of image classification in the Kili platform to save time while annotating images for a classification task. Vision transformers can be a good way to produce pre-annotations. Would you be interested in a content rather like "Importing in Kili image classification pre-annotations using a vision transformer"?

If yes can you provide us with a detailed outline and key steps of your tutorial?
If you are not familiar with Kili yet, you can have a look at our [documentation](https://cloud.kili-technology.com/docs/introduction/introduction-to-kili-technology.html)

Thank you and best wishes!

**Comment by ayyucedemirbas** [comment]
Thank you so much! I'm going to be working on a detailed outline. I'll let you know when it's done. Merry Christmas!

**Comment by ayyucedemirbas** [comment]
### My resource


**Topic:**

Importing in Kili image classification pre-annotations using a vision transformer


**Outline:**

In this tutorial, you will learn regression and classification, basics of image classification, data preparation, image classification with vision transformer using TensorFlow, and importing these classification results as Kili image classification pre-annotations. You will also learn how Kili image classification works and how to label your image data with Kili.

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
@ayyucedemirbas 
Sorry for the late reply, the end-of-year period froze operations.
We didn't select this article as it is. But it inspired us to make another article proposal on how to speed up annotation with autoML by constantly improving a pre-annotation model during the annotation. This article is described in #64 
You can have a look if you are interested!
