### ISSUE TITLE
[Article Proposal] How to train and deploy a ML model using TensorflowJS

### ISSUE THREAD

**Issue by parakalan** [kili-technology/kili-blogger-program#28]
### My resource

**Topic:** How to train and deploy a ML model using TensorflowJS 

**Outline:** In this tutorial, we'll see how to train a simple text classification model using TensorflowJS and deploy it on a simple javascript application. As data security becomes an issue, we need a better way to maintain data confidentiality. TensorflowJS helps us by training ML models on client side rather than on a server. 

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hello @parakalan 
Thank you for your interest and your article proposal.
This subject does not really fit in the Kili scope. The role of Kili Technology comes one step before the model development step. Our purpose is the Data and to help data scientists to optimize their model performances by working on the data and not on the model. Thus, We won't select this content proposal.

however, if you have good insights about model deployment, you might be interested in this article looking for an author : [Create a feedback loop for ML in production](https://github.com/kili-technology/kili-blogger-program/issues/3)

For your next article proposal, we ask you to write a more detailed outline, with bullet points and key ideas. It helps us to understand what you have in mind and increase your chance to get assigned to your article.

Thank you and best wishes!
