### ISSUE TITLE
[Request New Content] Music generation with Magenta

### ISSUE THREAD

**Issue by LaksCastro** [kili-technology/kili-blogger-program#29]
### My resource

**Topic:** Music generation with the pre-trained magenta models using `magenta.js`

**Outline:** In this article _how-to_ style we'll cover the basic understanding about how to generate melody using the `magenta.js` library, what we can and we can't do. The full project is a player in the browser that shows a player with generated music. Besides the main concept, music is something hard to work on real-world projects due to copyright limitations, but how about generating your own music?

`magenta.js` is a Javascript library build with `TensorFlow.js` that allow us use the API based on the Magenta pre-trained models

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by LaksCastro** [comment]
Also, I can write about this one if applicable, thanks

**Comment by theodu** [comment]
Hello @LaksCastro  
Thank you for your interest and your article proposal.
This topic is very interesting. We expect in the long term to develop data augmentation features on the platform but not data generation features. thus, we won't select this article proposal.

For your next article proposal, we ask you to write a more detailed outline, with bullet points and key ideas. It helps us to understand what you have in mind and increase your chance to get assigned to your article.

Thank you and best wishes!
