### ISSUE TITLE
[Article Proposal] Tutorial: Making (and testing!) classifiers with imbalanced datasets 

### ISSUE THREAD

**Issue by lbugnon** [kili-technology/kili-blogger-program#34]
### My resource

**Topic:**
Fundamentals on classification tasks when labels are imbalanced. 

**Outline:**
Introduction on why would you care about dataset imbalance. Considerations on training classifiers with such datasets. Fundamentals on setting up metrics that take this into account. The tutorial will contain fundamentals and code using standard python libraries (numpy, sklearn, pandas). Exercise will be guided in a jupyter/colab notebook.

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hello @lbugnon 
Thank you for your article proposal. I like this topic and it might be good to do a tutorial on it.
However, this tutorial should be linked to the Kili platform and API. Could you please provide a more detailed outline with key points of what you might say and how you link this content to Kili?

Thank you and best wishes!

**Comment by lbugnon** [comment]
Ok I'll see what can be done with Kili

**Comment by theodu** [comment]
Hi @lbugnon 
Sorry for the late reply, the end of the year period froze a bit operations.
This is a very interesting subject but it has already been addressed a lot on the internet and on other blogs. Thus we won't choose this article.
Don't hesitate to make other article proposals!
