### ISSUE TITLE
[Article Proposal] What is Confusion Matrix and Why Should We Use It?

### ISSUE THREAD

**Issue by turhancan97** [kili-technology/kili-blogger-program#35]
### My resource

**Topic:** What is Confusion Matrix and Why Should We Use It?

**Outline:** It is critical to accurately measure and evaluate the success of the machine learning model we have created.  It becomes easier to make improvements in the model and to work to produce predictions as close to reality by evaluating the correctly selected metrics. In this article, Confusion Matrix, one of the machine learning evaluation metrics, will be discussed in detail.

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by Yukti-09** [comment]
Hey, I hope that you are safe and well. Can I please be assigned to this article?

**Comment by theodu** [comment]
Hello @turhancan97 
Thank you for your interest and your article proposal.
It is an interesting topic, but it might be already very documented on the internet. We won't select your proposal.

For your next article proposal, we ask you to write a more detailed outline, with bullet points and key ideas. It helps us to understand what you have in mind and increase your chance to get assigned to your article.
Thank you and best wishes!
