### ISSUE TITLE
[Article Proposal] Fetching GitHub repository Traffic data using API v3

### ISSUE THREAD

**Issue by ashutosh1919** [kili-technology/kili-blogger-program#36]
### My resource

**Topic:** Fetching Traffic data of GitHub repository (clones and views) using GitHub API v3 is something that is very demanding but there are no blogs/articles available to do that. The article that I want to write will do that using `javascript`.

**Outline:**  
- Introduction to API v3
- Installation and project setup
- Writing `async` functions to fetch the data
- fetching the data and displaying results.

### My content is

- [ ✔️ ] A Kili Tutorial / Guide / How to article
- [ ✔️ ] An Article

**Comment by theodu** [comment]
Hi @ashutosh1919 
Thank you for your interest! 
I think that it is very useful content but it doesn't fit in Kili's scope. We won't select this article.

Happy New Year
