### ISSUE TITLE
[Article Proposal] How to build an AI powered Text Summarizer web app using gradio

### ISSUE THREAD

**Issue by EdemGold** [kili-technology/kili-blogger-program#37]
### My resource

**Topic:** Building AI applications that can actually be used in the real world is something that not a lot of tutorials cover. In this article, I will build a Text Summarizer web application using the open-source gradio library which provides GUI components for Machine Learning models, and deploy the web application on hugging face spaces.

**Outline:**
- Explain how AI Text Summarization works.
- Installation and project setup
- Downloading and initializing  summarizer model from hugging face
- Building gradio web app
- Deploying web app on hugging face spaces
### My content is
- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hi @EdemGold 
thank you for your tutorial proposal!
I find it very interesting. I like the fact that you use Hugging Face and Gradio. The idea would be to take an already trained summarize or to train it ? Where would Kili comes into this tutorial ?

**Comment by theodu** [comment]
Hi @EdemGold 
Your article could still interest us. Would Kili intervene in it?
Best

**Comment by EdemGold** [comment]
Hey @theodu, Yes the idea would be to take an already trained summarization model and then write a python script that segments large blocks of texts into little parts so the model can efficiently summarize large blocks of texts like books and a large number of articles and then build GUI components around the Machine Learning model using Gradio.



Is there any way Kili can intervene in this? 56

**Comment by theodu** [comment]
hi @EdemGold, then this is not in our scope. it is very model-oriented and lacks input on dataset management.
thank you for the proposal!
