### ISSUE TITLE
[Article Proposal] Quantization-aware Training vs. Post-training Quantization for Deep Neural Nets

### ISSUE THREAD

**Issue by dronefreak** [kili-technology/kili-blogger-program#39]
### My resource

**Topic:**

This article will give an outline about two techniques used for qunatization in deep learning, namely, post-training and quantization-aware training, discussing the advantages and drawbacks of both approaches.

**Outline:**

* Quantization, an introduction
* Quantization Schemes
* Quantization-aware training
* Post-training quantization
* Benefits and drawbacks

### My content is

- [x] An Article

**Comment by theodu** [comment]
hi @dronefreak 
Thank you for this article proposal. This does not fit with Kili's Scope. This article is very model training oriented.
Don't hesitate to propose articles more on annotation, data-centric AI or dataset creation.

Happy New year to you
