### ISSUE TITLE
[Request New Content] Creating a dataset for image segmentation

### ISSUE THREAD

**Issue by theodu** [kili-technology/kili-blogger-program#4]
### My Request

Creating a dataset for image segmentation

### Community vote
👍 Upvote if you like this topic

Thank you.

**Comment by bm777** [comment]
I can do this one :)

**Comment by theodu** [comment]
Hi @bm777,
Thank you for your outline, it seems great!
I will just need to wait until New year to validate it and assign you to it.
Also as a remark, the idea is to create a community able to share knowledge on how to use easily the Kili platform, your point 3. should exclusively speak about annotating the dataset on Kili and using the tools that we have on the platform ;)

Merry Christmas!

**Comment by theodu** [comment]
Hi @bm777 
I am now able to validate this article!
However, for part 3 of your outline, on tools to label, you will have to exclusively use the Kili Platform. Our segmentation tool is very mature. You can see all infos here : https://cloud.kili-technology.com/docs/interfaces-image/segmentation/
I assign you to it, you can begin to work on it

**Comment by bm777** [comment]
I got the point :)
How about the delay of the task?

**Comment by theodu** [comment]
Do you mean the time to write the article? There is no determined expected time. We understand if you have time constraints, that is very fine. We are very flexible. Just keep me in touch about when you expect to write your first draft ;)

**Comment by bm777** [comment]
I will finish it before the 15th February :)

**Comment by theodu** [comment]
Hello @bm777, how are you doing with this content?

**Comment by JustBrn** [comment]
Hi @bm777, any news on this? Thanks!

**Comment by bm777** [comment]
Hi @theodu and @JustBrn Sorry for the long silence, I was in Russia since February.
The situation was not quite for me. So I had to reallocate.

A few days ago I checked it, but the link https://cloud.kili-technology.com/docs/interfaces-image/segmentation/  was not working.

I'm asking myself if it is the same as this one: https://cloud.kili-technology.com/docs/getting-started/getting_started-image_semantic_segmentation/

**Comment by theodu** [comment]
Hi @bm777,
Sorry for this link issue, we are working a lot on our documentation to update it and to make it nicer.
You can indeed find all Infos on this link: https://cloud.kili-technology.com/docs/getting-started/getting_started-image_semantic_segmentation/

**Comment by bm777** [comment]
okay then thanks @theodu

**Comment by JustBrn** [comment]
@bm777 do you have everything you need to write this tutorial then? Or do you still need us to help you with something?

**Comment by bm777** [comment]
@JustBrn yeah i would like to have a sample, in such a way a template.

**Comment by theodu** [comment]
Hi @bm777 What do you mean by sample ? a template of what?
best
théo

**Comment by bm777** [comment]
Just like a preview of a tutorial done.
Just to see what should be the final result.

or we should only make articles in a google document ?

**Comment by bm777** [comment]
@theodu que thanks so much.

It is the information I wanted to know.

And for the Template 👍

**Comment by JustBrn** [comment]
Hi @bm777 how are you? Have you been able to work on this article? Thanks!

**Comment by bm777** [comment]
@JustBrn Hi, I'm fine.
I signed up for the kili platform, but I still do not have access to the platform for the Part II of the Article.

The google draft I did for the part I: https://docs.google.com/document/d/1P31aRlVY5U4Y7XAw34If9_25BHKErlYLxVRDlg8f0yo/edit?usp=sharing

**Comment by theodu** [comment]
Hi @bm777 
Can you give me the email that you used to sign in in the platform ? I will provide you with a premium account so you can use it for your article.
I will begin to review the part 1!
Cheers
Théo

**Comment by bm777** [comment]
this email: ***@***.***

**Comment by bm777** [comment]
Hi @theodu, you can review the part 1.
This email: bayangp0@gmail.com

**Comment by theodu** [comment]
@bm777 
I don't see your user on the platform with this email. Did you create an account here: https://cloud.kili-technology.com/ ?

**Comment by bm777** [comment]
No, I went to the product I mean.

just created an account with the link you shared :)

**Comment by bm777** [comment]
@theodu how about the part I ?

**Comment by theodu** [comment]
Ah good, I updated your license, can you now check if you can still connect to the platform ?

**Comment by theodu** [comment]
> @theodu how about the part I ?
Hi didn't have the time to review it, I will let you know as soon as I review it. And I will leave feedback on the google docs

**Comment by bm777** [comment]
> Ah good, I updated your license, can you now check if you can still connect to the platform ?

Yeah, I'm having access right now.
Thank you :)

**Comment by theodu** [comment]
Hi @bm777 
I just reviewed your part 1 of your article. 
2 things:
1- it is 90% copy pasted from https://docs.aws.amazon.com/rekognition/latest/customlabels-dg/md-coco-overview.html 
Plagiarism is highly punishiable and has big legal consequences. and we can't work with such authors
2- For a copy pasted content, it has no added value. We can't work with authors that just want to batch their work.
For this two reason, I hope that you understand that we cannot continue to work with you. 

Thank you for your comprehension, good continuation
Théo

**Comment by bm777** [comment]
@theodu, maybe it's a misunderstanding, 
I based myself on the global properties of a dataset in the coco format published here: https://cocodataset.org/#format-data
As you know that it is not the complete doc. Normally I should present the COCO format on a dataset that I have already labelled on the Kili platform. 
So, while I was waiting for access under the Kili platform, I embarked on a draft which is not final and which you took as part I complete.

Look as well, it is only COCO format copied from the source you mentioned, the part I should be based on part II.

**Comment by JustBrn** [comment]
Hi @bm777, 
I work with Théo at Kili Technology. Unfortunately, the draft you shared is entirely and directly copy pasted from this [documentation](https://docs.aws.amazon.com/rekognition/latest/customlabels-dg/md-coco-overview.html), with no attempt at rephrasing. Even as a draft, this shows clear intention of copy pasting and fast tracking to an article that would be unusable for us.
We are very strict on plagiarism, so while we always welcome great original content, we cannot continue this collaboration. 

Best, 
Justine
