### ISSUE TITLE
Analysing Time Series Forecasts for Forex and Stock Market Trends using Recurrent Neural Networks

### ISSUE THREAD

**Issue by kartikmadan11** [kili-technology/kili-blogger-program#40]
### My resource

Time series data is data that is chronologically assembled, indexed or listed. OHLC charts can represent time series for market data with period defined by the analyst. This article would look into Time Series Forecasting and it's credibility in forecasting of time-series data using information and trends gathered from past and present values.

**Topic:** Analysing Time Series Forecasts for Forex and Stock Market Trends using Recurrent Neural Networks

**Outline:** Forex Trading is performed on online trading platforms with various statistical approaches for analysis of trends. This 
approach applies a black box technique using Artificial Recurrent Neural Networks to analyze the market trends and make time-series forecasts. Architectures used are LSTM and GRUs.

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
Hi @kartikmadan11 
Times series is the new data type that we handle at Kili. it would be nice to have an article on it. However, this article is very model-oriented and at Kili, we focus more on the dataset. Do you have any content that would give good tips about managing the data of a time series model ?

**Comment by kartikmadan11** [comment]
Hi @theodu. Although the article is model oriented, pre-processing a time series dataset is very important and I've worked on that before.

**Comment by theodu** [comment]
Hi @kartikmadan11 
That sounds great. I admit that I never manipulated a dataset of time series and I think that it could be a very interesting topic! I propose the article and come back to you asap

**Comment by theodu** [comment]
Hi @kartikmadan11 
Sorry for the late reply, the end of the year period froze a bit operations.
We decided not to prioritize content on Time Series. This is a data type that we handle but we still need to work on it before. Thus we won't choose this article.
Don't hesitate to make other article proposals!
