### ISSUE TITLE
[Article Proposal] - Image Classification using Knowledge Distillation

### ISSUE THREAD

**Issue by sayannath** [kili-technology/kili-blogger-program#41]
### My resource

**Topic:**
Image classification using Knowledge Distillation

**Outline:**
* Introduction
* Prepare the dataset.
* Create the student model and teacher model using Functional API using Keras.
* Discuss the `function matching` recipe.
* Train the teacher model.
* Distill the teacher model to student model
* Train student model from scratch for comparison.
* Full Code walkthrough will be there.

### My content is
- [x] An Article

**Comment by sayannath** [comment]
Hi! @theodu I want to write an article on this topic and also talk about the recipes of Knowledge Distillation.

**Comment by theodu** [comment]
hi @sayannath 
That is nice, I didn't know this concept before. I will discuss it with an expert in our team to see if it could be relevant to the blog. I will have to wait 1 week until his return from Christmas Holiday. I keep you in touch. 

In the meantime, when training a student network, how do you choose the dataset? If we need specific tips on how to create a dataset for knowledge distillation, it could be interesting in our blog

**Comment by sayannath** [comment]
> hi @sayannath That is nice, I didn't know this concept before. I will discuss it with an expert in our team to see if it could be relevant to the blog. I will have to wait 1 week until his return from Christmas Holiday. I keep you in touch.
> 
> In the meantime, when training a student network, how do you choose the dataset? If we need specific tips on how to create a dataset for knowledge distillation, it could be interesting in our blog


Thinking to use a TensorFlow Dataset like Flower. My sole purpose is to make a tutorial.
Cheers!!

**Comment by theodu** [comment]
Hi @sayannath 
Sorry for the late reply, the end of the year period froze a bit operations.
I liked the topic but it is a bit out of scope for the Kili Blog. Thus we won't choose this article.
Don't hesitate to make other article proposals!
