### ISSUE TITLE
[Article Proposal] - How can AI be used to prevent violence against women?

### ISSUE THREAD

**Issue by Yukti-09** [kili-technology/kili-blogger-program#44]
### My resource

The article will focus on how AI can be used to prevent violence against women and to help safeguard them 

**Topic:**

Ideas as to how AI be used to safeguard women

**Outline:**

1. Introduction
2. Flag areas where crimes against women are prevalent.
3. Using chatbots to assist women in times of domestic abuse.
4. Recognize women trafficking 
5. Conclusion

### My content is

 :white_check_mark: An Article

**Comment by theodu** [comment]
HI @Yukti-09 
Can be a nice article, very transverse and on a societal topic. How can you emphasize data for such a topic?

Happy New year

**Comment by Yukti-09** [comment]
Hey, thanks!

I will focus more on data ethics and the issues associated with each of the points.

Happy New Year!

**Comment by theodu** [comment]
Hi @Yukti-09 
Sorry for the late reply, the end of the year period froze a bit operations.
This article is too transverse to bring real value to Kili. I liked the subject though. Thus we won't choose this article.
Don't hesitate to make other article proposals!
