### ISSUE TITLE
[Article Proposal] Impact of Machine Learning on our lives (past, present and future) 

### ISSUE THREAD

**Issue by Yukti-09** [kili-technology/kili-blogger-program#46]
### My resource
The article will focus on the evolution in our lives with the help of machine learning and deep insight as to what the future will be.

**Topic:**

Impact of Machine Learning on our lives

**Outline:**

1. Introduction
2. Our lives without machine learning
3. The present life with machine learning
4. What more can machine learning do?
5. Conclusion 

### My content is

 :white_check_mark: An Article

**Comment by theodu** [comment]
Hi @Yukti-09 
Thank you for the proposal. however, this topic is a bit too broad and has already been addressed a lot on other blogs.
We won't select this article.

**Comment by Yukti-09** [comment]
Hey!

Got it! Thanks for the feedback, will try improving!
