### ISSUE TITLE
[Article Proposal] Making Smart Business Decision: The Importance of Big Data

### ISSUE THREAD

**Issue by Renerd-max** [kili-technology/kili-blogger-program#47]
### My resource

**Topic:** Making Smart Business Decision: The Importance of Big Data.

**Outline:**
-An introduction outlining the importance of data and the use of big data technology, such as kili in making smart business decision.
-A definition of big data
-How big data can benefit the growth of any business
-How to apply big data to the growth of a business (using Kili technology)
-The future of big data across industries
-Conclusion.

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
Hi @Renerd-max 
Very broad subject, already addressed a lot in other blogs but always interesting.
I come back to you to give you an answer asap.

**Comment by theodu** [comment]
Hi @Renerd-max 
Sorry for the late reply, the end of the year period froze a bit operations.
Big Data is not our core. Our reason why at Kili is the data-centric approach. Thus we won't choose this article.
Don't hesitate to make other article proposals!
