### ISSUE TITLE
[Article Proposal] Data Augmentation

### ISSUE THREAD

**Issue by Yukti-09** [kili-technology/kili-blogger-program#51]
### My resource
The article will focus on data augmentation.

**Topic:** 

Data Augmentation

**Outline:**

1. Introduction
2. Datasets without augmentation
3. Methods of augmentation for images and text 
4. Negative effects of augmentation
5. Conclusion

### My content is

 :white_check_mark: An Article

**Comment by theodu** [comment]
Hi @Yukti-09 
This subject has already been proposed by some bloggers. 
Best
