### ISSUE TITLE
 Image classification using transformers

### ISSUE THREAD

**Issue by TanyaChutani** [kili-technology/kili-blogger-program#53]
### The concerning content
Topic:
    Image classification using transformers

Outline:
    Introduction about the topic
    Prepare the dataset using our tool
    Create the model using Functional API using Tensorflow2.x.
    Train model with different augmentations.
    Compute f1 score on test datatset
    A complete code walkthrough would be available

**Comment by theodu** [comment]
Hi @TanyaChutani 
Thank you for your article proposal. Such an article has already been proposed and is under investigation.
For next article proposals, please keep the automatic template

Best wishes
