### ISSUE TITLE
[Article Proposal] How to make Object Detection using TFOD API

### ISSUE THREAD

**Issue by sayannath** [kili-technology/kili-blogger-program#54]
### My resource

**Topic:**
Make an Object Detector Using TensorFlow Object Detection API
**Outline:**

### My content is
* Collect data
* Anotate the data
* Create `TF Record`
* Setup TFOD API
* Train the detector
* Export the detector
* Test the detector

- [x] An Article

**Comment by theodu** [comment]
Hi @sayannath 
I propose this article and come back to you asap

Best wishes

**Comment by theodu** [comment]
Hi @sayannath 
We liked this article. You tagged it as an article but I think that it could have a great impact if it is more hands-on and shown as a tutorial. Also, the last part of the tutorial should be running your model on a dataset and importing those predictions as pre-annotation in Kili. Like this, it will show the way to people wanting to pre-annotate their dataset on Kili with object detection. I can of course help you to understand the platform if needed.
Does it suit you?

**Comment by sayannath** [comment]
Yes, I will do make this a tutorial. I am up for it.

**Comment by theodu** [comment]
Great, then I assign you to the article, you can begin to work on it!

**Comment by theodu** [comment]
@sayannath Great, then I assign you to the article, you can begin to work on it!

**Comment by sayannath** [comment]
> @sayannath Great, then I assign you to the article, you can begin to work on it!

Cool.

**Comment by sayannath** [comment]
It will take me one week to complete this.

**Comment by theodu** [comment]
ok, thank you for the update!

**Comment by JustBrn** [comment]
Hi @sayannath, 

Nice to meet you! I'm working with Theo on the Blogger Program here. I'm just checking in following your last messages. How is the writing going? Do you have everything you need to write this tutorial?
Let me know if you need us on something :)

**Comment by JustBrn** [comment]
Hi @sayannath since we haven't heard from you, I'll close this issue. Feel free to come back to us and restart the project ! Thanks
