### ISSUE TITLE
[Article Proposal] Mixed Precision Training

### ISSUE THREAD

**Issue by sayannath** [kili-technology/kili-blogger-program#55]
### My resource

**Topic:**
How to train your model using mixed precision
**Outline:**
* Data Collection
* Data preprocessing
* Mixed Precision - Theory
* Train model
* Predict the model

### My content is

- [x] An Article

**Comment by theodu** [comment]
Hi @sayannath 
This subject is very model-side and does not involve data management enough for the Kili Blog. We won't take this article

best wishes
