### ISSUE TITLE
[Article Proposal] Scaled YOLOV4 in PyTorch

### ISSUE THREAD

**Issue by sayannath** [kili-technology/kili-blogger-program#56]
### My resource

**Topic:**
Make a Scaled YOLOV4 using PyTorch

**Outline:**
* Collect data
* Annotate the data
* Setup Scaled YOLOV4
* Train the detector
* Export the detector
* Run Test on the detector

### My content is

- [x] An Article

**Comment by theodu** [comment]
Hi @sayannath 
There is already an issue on the subject : #6 
Best wishes
