### ISSUE TITLE
[Article Proposal] How to make an object detector for your browser

### ISSUE THREAD

**Issue by sayannath** [kili-technology/kili-blogger-program#57]
### My resource

**Topic:**
Make an object detector model to run in your browser using TensorFlow JS

**Outline:**
* Collect the data
* Annotate the data
* Setup TFOD API
* Train the detector
* Export the detector
* Convert the exported model into TFJS format
* Setup React App Web App to do inference

### My content is

- [x] An Article

**Comment by theodu** [comment]
Very close to #54 ,
I will only keep the other issue
