### ISSUE TITLE
[Article Proposal] How to make image classifier Using TensorFlow Hub

### ISSUE THREAD

**Issue by sayannath** [kili-technology/kili-blogger-program#58]
### My resource

**Topic:**
How to make image classifier Using TensorFlow Hub

**Outline:**
* Data Collection
* Data loader
* Make the model via TensorFlow Hub
* Train the model
* Predict on the model
* Calculation confusion matrix as well as classification report.

### My content is

- [x] An Article

**Comment by theodu** [comment]
Hi @sayannath 
This topic is closed to #54. We validated #54 so we won't select this one.
best
