### ISSUE TITLE
[Article Proposal]  Fundamental principles of data management

### ISSUE THREAD

**Issue by Yukti-09** [kili-technology/kili-blogger-program#59]
### My resource
The article will focus on the principles of data management.

**Topic:** 

Fundamental principles of data management

**Outline:**

1. Introduction
2. Principle 1: Data Management Strategy 
3. Principle 2: Data Standards
4. Principle 3: Data Integration
5. Principle 4: Data Quality 
6. Conclusion

### My content is

 :white_check_mark: An Article

**Comment by theodu** [comment]
Hi @Yukti-09 
There are already many article proposals on this subject at the time. 
Best wishes

**Comment by Yukti-09** [comment]
Got it, thank you!
