### ISSUE TITLE
[Request New Content] Object Detection on Custom Dataset with YOLO (v4) using PyTorch

### ISSUE THREAD

**Issue by theodu** [kili-technology/kili-blogger-program#6]
### My Request

Object Detection on Custom Dataset with YOLO (v4) using PyTorch

### Community vote
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by TanyaChutani** [comment]
I can take this up, however, I would love to do this with the latest version of Tensorflow (TF2.x)

**Comment by alperiox** [comment]
I'm using PyTorch and I've done different computer vision projects before. I also have different Yolov4 implementations in PyTorch which can be used for fine-tuning the pre-trained model. I can use Kili's image bounding box labeling utilities to build the custom dataset.

**Comment by theodu** [comment]
Hello @TanyaChutani @alperiox 
Thank you for your interest! That is great. 
In order to get assigned to an article, can you please provide a detailed outline of the tutorial?
Best wishes

**Comment by alperiox** [comment]
Definitely!


Introduction:
After introducing YOLOv4 and object detection shortly, we'll try to build an object detector that can detect trees or generally plants. We build our dataset from scratch by using Kili's labeling tools and fine-tune a pre-trained YOLO detector using PyTorch.

Goals:
After the tutorial, the reader would be able to build custom datasets for object detection tasks and have an idea about object detection model fine-tuning.  Therefore they can use both the tutorial and platform for their future object detection projects. 

Prerequisites:
The reader just needs to install PyTorch dependencies, Kili labeling tools can be used online so an account for that is also necessary.

Finally, I'll create a github repository for the project that contains the model along with the dataset.  @theodu

**Comment by theodu** [comment]
Hi @alperiox,
This outline seems great! 
You also had very good ideas about the Kili X Hugging Faces tutorial. I wait until New Year Eve to see with the team which article has to be prioritized between both and I come back to you.

Merry Christmas!

**Comment by theodu** [comment]
Hi @alperiox 
I assign you to this article and put it on hold, waiting for you to finish your article on HuggingFace #5

**Comment by theodu** [comment]
Hi @alperiox
This content isn't really any more a target for us. 
We liked a lot your article on Hugging Face and the new target is to produce similar content with other AI frameworks. would you be interested in writing other content such as the one you did?
Did you already work with Datarobot or Domino Data Lab?

**Comment by alperiox** [comment]
Hello @theodu. I haven't used them before but I checked and liked them both! Exceptionally, Domino Data Lab seems to have pretty cool solutions. I see that DataRobot has a wide range of options. It is literally a fully-fledged platform for automated ML from processing the data to the deployment. 
But I have very little or no experience in especially MLOps. Therefore while I'm still interested in writing articles like the Hugging Face one, I believe my lack of experience will impact the performance. I think I can still come up with a basic use case for both platforms like I did with the Hugging Face article.

**Comment by theodu** [comment]
Hi @alperiox Thank you for your answer,
Alright. 
Otherwise, I put here other framework targets: Dataiku, Google Cloud Machine Learning Engine, Microsoft Azure Machine Learning service, H2O.ai, OctoML. 
Do you have experience in any of them?

**Comment by alperiox** [comment]
Hey @theodu. I've used Dataiku, H2O, and Azure before. I believe I can implement an easy-to-follow, basic pipeline for businesses.

**Comment by theodu** [comment]
Wonderful!
I let you think of a good use case and make a new issue for an article?
I don't know how many of these frameworks you would like to integrate into your article. These contents have to be tutorials, it takes more time to write. I let you think if you want to integrate them 1 by 1 and make other frameworks in other contents or if you want to use both in the same tutorial etc.

**Comment by alperiox** [comment]
Sure thing! I'd like to integrate them one by one, I think it is better to target a specific audience in the tutorials. Also, it may be difficult for the reader to follow.

**Comment by JustBrn** [comment]
Hi @alperiox, opening this back after a long pause :)
Are you still willing to work on this article? Thanks!

**Comment by alperiox** [comment]
Hello @JustBrn! I'd love to! I just need to collect some data, then it should be okay :)

**Comment by JustBrn** [comment]
@alperiox alright, that works! Let me know when you're ready to start :)

**Comment by JustBrn** [comment]
Hi @alperiox how is it going with this? Happy to get news.

**Comment by alperiox** [comment]
Hey @JustBrn! I believe I have enough data now. I planned the project outline and will be working on it after the 25th of May because of my finals.

**Comment by alperiox** [comment]
Hey @JustBrn! I'm working on the project, would there be any problems if I use [this implementation](https://github.com/WongKinYiu/PyTorch_YOLOv4)? I could also prepare a custom implementation by myself but it'd take a bit long.

**Comment by theodu** [comment]
Hi @alperiox 
Sorry there was a misunderstanding on our side. In Mid February, we put this article on hold, because we already had an article with Yolo. Instead, I proposed you if we could make an article with DataRobot or Domino Data Lab, another framework from the ecosystem, like the one that you did with Hugging Faces.
The new main target is to focus on articles showing how to use Kili with another framework.
Did you think about it ?

Best,
Théo

**Comment by alperiox** [comment]
Hello @theodu! Not a problem, I will propose an article outline about using DataRobot and Kili Technology platform together

**Comment by theodu** [comment]
Great @alperiox ! please make a new issue for it, I close this one.
Cheers
Théo
