### ISSUE TITLE
[Article Proposal] How to measure the quality of a dataset labeled by multiple people

### ISSUE THREAD

**Issue by fernandojvdasilva** [kili-technology/kili-blogger-program#60]
### My resource

There are certain problems in which the label assigned to the data is somehow "arbitrary", which means that the label depends on the opinion or perspective of the annotator. As an example, suppose a text dataset that we want to label as positive or negative sentiment. Notice that the sentiment may not be clear for all the samples.

In cases like this, we may use multiple participants and take the label assigned by the majority of them. When we have this scenario, we can measure the agreement of annotators for each labeled sample and even the whole dataset by calculating *Fleiss' Kappa*.

In this article, we give an intuition of the Fleiss' Kappa, with a sample of its application for labeling a sentiment analysis dataset.

**Topic:**

*** How to calculate the Fleiss' Kappa and when it applies ***

*** Example: measuring agreement of sentiment analysis labeling ***

*** How to interpret Fleiss' Kappa results ***

*** Criticism and related issues ***

**Outline:**

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
Hi @fernandojvdasilva 
I didn't know the Fleiss' Kappa before, thank for this new knowledge ;)
However, we already have consensus metrics on the platform that are updated constantly while annotations are done.
I think that it is a very interesting subject but I don't see how this specific topic and outline could bring impactful content to people using Kili. 

An article that would be great would explain for each ML task how we calculate the consensus on the platform, what are their pros and cons, and maybe give examples of alternatives (Fleiss' Kappa could be one for classification).
Such content would introduce the importance of consensus in annotation and give more transparency on how we calculate consensus on the platform
This explains how we calculate consensus at Kili for the different ML tasks:  https://cloud.kili-technology.com/docs/quality/consensus/#docsNav 
Are you inspired by this topic @fernandojvdasilva ?

**Comment by fernandojvdasilva** [comment]
> Hi @fernandojvdasilva I didn't know the Fleiss' Kappa before, thank for this new knowledge ;) However, we already have consensus metrics on the platform that are updated constantly while annotations are done. I think that it is a very interesting subject but I don't see how this specific topic and outline could bring impactful content to people using Kili.
> 
> An article that would be great would explain for each ML task how we calculate the consensus on the platform, what are their pros and cons, and maybe give examples of alternatives (Fleiss' Kappa could be one for classification). Such content would introduce the importance of consensus in annotation and give more transparency on how we calculate consensus on the platform This explains how we calculate consensus at Kili for the different ML tasks: https://cloud.kili-technology.com/docs/quality/consensus/#docsNav Are you inspired by this topic @fernandojvdasilva ?

Hi @theodu!

Oh, I got it! I didn't know there were methods to calculate the consensus on Kili, that's why I proposed the article about Fleiss' Kappa, but I completely understand that it makes a lot more sense to write about how the consensus is calculate for each ML task as you recommended! I will do some research here to understand a little more about this matter then I will rewrite the article proposal.

**Comment by theodu** [comment]
Hi @fernandojvdasilva 
Good to hear it. I am looking forward to seeing this article proposal!
Thus, I close this issue.
