### ISSUE TITLE
[Article Proposal] What is TinyML and how does it affects Machine Learning best Practices

### ISSUE THREAD

**Issue by Renerd-max** [kili-technology/kili-blogger-program#62]
### My resource

**Topic: What is TinyML and how does it affect Machine Learning best Practices**

**Outline:**
**Introduction:** A definition of TinyML and it's applications
**Sub-Part 1: The Potential of TinyML in machine learning**
**Sub-Part 2: How TinyML makes Machine Learning more accessible**
**Sub-Part 3: Importance of using TinyML for Machine Learning**
**Sub-Part 4: Tools for building models for TinyML**
**Sub-Part 5: The future of TinyML**
**Conclusion**

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
hi @Renerd-max 
This topic isn't really related to data management or anything like this. It an interesting topic but is a bit out of scope for Kili
