### ISSUE TITLE
[Article Proposal] How to Use Data to Build Products that make Impacts

### ISSUE THREAD

**Issue by Renerd-max** [kili-technology/kili-blogger-program#63]
### My resource

**Topic: How to Use Data to Build Products that make Impacts**

**Outline: **By the end of this guide, readers should be able to:
-Know the importance of data in making product decisions
-Identify the best approach to making product decisions, using data.
-Learn how to outsource relevant data that are crucial to the success of a product.
-Understand how they can plan their next product using data platforms to process available data.
-Gain an insight into a practical case study.
-Be able to build a product that makes an impact using data.
**Introduction**: a brief introduction, outlining the importance of making impactful products and how costly a failure can be.
**Sub-Topic 1: Best Approach to Making product decisions, using data:** These include quantitative approach, involving product analysis, usability metrics, customer satisfaction, etc. And qualitative approach, involving interviews, concept analysis, usability analysis, etc.
**Sub-Topic 2: Processing your Data:** Highlights how to use data labeling platforms and tools to build models that can aid in understanding our data, and a guide on how to do this.
**Sub-Topic 3: A Case Study:** Highlighting how to make impactful products using a case study.
**Conclusion**

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hi @Renerd-max 
Thank you for this outline.
This is very related to business and big data. We rather focus on data-centric approach to improve model performance. It is a bit out of scope.
