### ISSUE TITLE
[Request New Content] AutoML for faster labeling with Kili Technology

### ISSUE THREAD

**Issue by theodu** [kili-technology/kili-blogger-program#64]
### My Request

AutoML if well used can skyrocket annotation speed! The idea of the workflow is to:
- import an unlabeled dataset on Kili to annotate it
- annotate a few data
- the autoML pipeline triggers and fine-tune a model to annotate other data
- this model does predictions on the unlabeled data and import it on the platform
- this speed-up the annotation process as the data is already pre-annotated when a human annotate the data on the platform
- Each time that N new data has been annotated on the platform, it triggers again the autoML pipeline, fine-tunes the model, and re-import new predictions for the unlabeled data.

A recipe has already been written on this, which is a huge help on the topic. https://github.com/kili-technology/kili-playground/blob/master/recipes/automl_text_classification.ipynb 

This article should present this method and show how it can save a lot of annotation time. You should also make sure that the recipe still works well and maybe improve it if you have ideas. The recipe is written for text, but an example in the article with images would be nice to show the versatility of the method.

### Interactions
👍 Upvote if you like this topic
Comment with a detailed outline if you can write this content

Thank you.

**Comment by FnSK4R17s** [comment]
## Summary
Annotating Datasets can be a really time-consuming process. However, It doesn't need to be like that. We can leverage the power of Machine Learning to speed up our annotation process. In this article, we will go over two examples where we will use AutoML techniques in conjunction with Kili Technology to speed up our annotation process. First, we will go over a text classification use case where we will use the AutoSKLearn library to train an AutoML model to help annotate a text dataset. In our second example, we will go over an Image dataset where we will use AutoKeras Library to train an AutoML model to help annotate an Image Classification Dataset.

## Outline
- Introduction
- What is AutoML
- How can AutoML help us in saving precious labelling time?
- How does AutoML work under the hood?
- Popular Open Source and Paid AutoML frameworks
- Integrating AutoML with Kili Technology
- Example 1: Text Dataset with AutoSKLearn and Kili Technology
- Example 2: Image Dataset with AutoKeras and Kili Technology

## Optional Topics
- Few-Shot Learning and its applications in AutoML

**Comment by theodu** [comment]
hi @FnSK4R17s 
Nice outline! Mentioning a part on few-shot learning is interesting, mainly because the first training is done on few data only. If you can make a paragraph on it, it is a +

I assign you to the article, you can begin to work on it

**Comment by FnSK4R17s** [comment]
@theodu thanks !
Started writing this article.

**Comment by FnSK4R17s** [comment]
Hey @theodu 
Thanks for asking. I have written the article along with two jupyter notebooks for text and image classification use cases. Sadly I haven't been able to edit my draft because of prior work commitments. I'll do this on priority and submit it for review as soon as possible.
Regards,
Shikhar

**Comment by theodu** [comment]
Hi @FnSK4R17s 
Thank you for the update!

**Comment by JustBrn** [comment]
Hi @FnSK4R17s, 

Nice to meet you! I'm working with Theo on this blogger program. Just checking in -  do you have everything you need to finish this article? 

Thanks!

**Comment by JustBrn** [comment]
Hi @FnSK4R17s, how you're doing well! How are things going on this article?

**Comment by JustBrn** [comment]
Hi @FnSK4R17s, any news on this? Happy to hear from you :)

**Comment by JustBrn** [comment]
@FnSK4R17s Hi! Since we do not hear from you, I'll close the issues related to our collaboration. Feel free to come back to us in the future to start things up again ! Thanks
