### ISSUE TITLE
[Article Proposal] Building a Data Flywheel for ML in Production

### ISSUE THREAD

**Issue by FnSK4R17s** [kili-technology/kili-blogger-program#65]
### My resource

**Topic: Building a Data Flywheel**

## Summary
Data Flywheel is an interesting concept. It enables us to improve our machine learning model while it is in Deployment. The concept is simple yet effective. First, we train a model and deploy it in production. Then the model brings in a few users who generate data. This data is used to train a new model which in turn brings in new customers and the cycle continues. A typical Data Flywheel consists of the following key parts:
- Data Collection
- Data Cleaning and Labeling
- Model Training
- Generating Model Report
- Model Testing
- Model Deployment
- Model Monitoring

## Outline
- Data collection strategy
- Data cleaning and labelling strategy (generating data slices) #66
- Model training strategy (when to train a new model)
- Reporting Model Performance (Model cards)
- Model Testing strategy (using data slices)
- Model Deployment strategy (A/B testing)
- Model Monitoring (Approximate Performance Metrics)

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
Hi @FnSK4R17s 
I really like it! I accept this article but we will need to wait before writing it. 
You are currently assigned to an article and we currently have a lot of articles in the pipeline. I put this one on hold and I come back to you when we are ready to launch the writing of this article!

**Comment by JustBrn** [comment]
@FnSK4R17s Perfect!
