### ISSUE TITLE
[Article Proposal] Creating Slices from our Datasets

### ISSUE THREAD

**Issue by FnSK4R17s** [kili-technology/kili-blogger-program#66]
### My resource

**Topic: Slicing a Dataset**

## Summary
Large datasets are difficult to analyse. Although we can check whether a dataset has an equal number of examples for all classes but in the dataset might be unbalanced in other ways. For example, let's assume that we have a dataset of people who have suffered a heart attack, we might notice that even if we have an equal number of examples where the patient survived and where the patient did not survive. It is quite common that younger patients are underrepresented in the dataset as compared to more senior patients. This can cause a model trained on this dataset to behave irrationally and predict that every young patient will have a high probability of survival. Because while training, a really small amount of test examples were from younger patients so the contribution of these examples to the total accuracy metric was very small.

To solve this problem we evaluate our model based on data slices. In this article, we will try to understand how data slices are created and try to automate the process using machine learning.

## Outline
- What are data slices?
- How to efficiently partition our datasets into meaningful slices
- Using Metadata to create slices
- Using Heuristics to create slices
- Using Unsupervised learning to segregate data into slices
- Slice based data labelling
- Ensuring that the labels are consistent across slices
- Comparing model performance on the sliced dataset

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
Hi @FnSK4R17s
this is also an article that I really like! I accept this article but we will need to wait before writing it.
You are currently assigned to an article and we currently have a lot of articles in the pipeline. I put this one on hold and I come back to you when we are ready to launch the writing of this article!
