### ISSUE TITLE
[Article Proposal] Image data collection, training using yolov5 and deployment using django rest framework

### ISSUE THREAD

**Issue by mrdvince** [kili-technology/kili-blogger-program#69]
### My resource
An article covering collecting image data (fruit types as an example case) training and deployment.

**Topic:** Training and deploying a custom objection model using yolov5 and Django

### Summary
The main goal of the article is to help the reader be able to go from having an object detection idea, acquiring the data, training the model, and finally being able to put it in a production environment.

**Outline:**
- Easily provision a GPU VM on AWS (infrastructure) using terraform, makes it easy to create and destroy cloud resources.
- Easily scrape fruit images from the internet and clean the data
- Annotate the images
- Data versioning using weights and biases artifacts
- Training and viewing metrics and model artifacts on wandb
- Finally deploy the model as an API using Django, the Django rest framework, and docker

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
Hi @mrdvince 
Thank you for your proposal and sorry for the time to answer!
I like the fact that the article gives an end-to-end solution. However, we already have an article in progress/on hold on object detection using Yolov4 #6. Even if your article would go deeper, we should wait for this article to be written to avoid redundancy.
Best
Théo

**Comment by mrdvince** [comment]
Hello @theodu 
Sure sounds good.

**Comment by theodu** [comment]
Hi @mrdvince 
How are you doing?
We have a new focus on our blog strategy. AI is split into many different frameworks and Kili is only a brick of the whole ecosystem. We would like to show how to connect Kili to other frameworks. Your content would introduce a lot of these frameworks and that is a very good thing! We would like such content to be tutorials and not articles. Like this, it would help anyone to use Kili with other frameworks with already written code. Does this content seem feasible for you as a tutorial? if this is too much, it can be split 2 or 3 tutorials.
Tell me what you think about it!

**Comment by mrdvince** [comment]
Hi, @theodu am doing good; yeah it's feasible, I could split this into 2 tutorials, one mainly focusing on the deep learning bits and the other one focusing on the deployment of the trained models.

**Comment by theodu** [comment]
Hi @mrdvince 
That sounds great! Let's at least begin with the first one.
can you please write here an outline for the first tutorial? 
in your previous outline, you spoke about fruit types as an example case. This is quite an academic use case, could you find one closer to what a company might use ?

**Comment by theodu** [comment]
I don't have any industry in mind. As the people targeted by the article are senior data scientists, the idea is just to take a dataset that is not academic/too simple to give legitimacy to the content. I let you find the one that suits you !

**Comment by mrdvince** [comment]
@theodu I think aerial object detection could come in handy for traffic use cases esp in urban settings.
here is a breakdown of the outline,
- [ ] Getting the data (scrape images from duck duck go)
entails creating a dataset from scratch (and this can be used for any use-case) someone would have.
- [ ] Annotate the images (following the Yolo v5 format)
- [ ] Data versioning using Weights & Biases artifacts
using w&B artifacts to version the data helps especially when running training jobs from different machines and also in scenarios where training jobs are interrupted e.g on colab.
- [ ] Spinning up cloud instances using terraform (makes for more convenient management of resources).
using terraform you can easily provision a GPU instance and once done destroy all the resources hence can be sure nothing has been left that might cause being billed later on. Plus with the added advantage of being fast to set up. (just a single command)
- [ ] Training using Yolo v5 and viewing the logs on W&B.
- [ ] and finally, Model versioning using DVC (data version control) and storing the models on S3 buckets.

**Comment by theodu** [comment]
I love it. The use case is also very good I think.
The outline is very good! for the annotation phase, use Kili of course, I can upgrade your license if needed!
I assign you to the tutorial, you can begin to work on it ;)

**Comment by mrdvince** [comment]
Awesome, I will start creating a dataset and start working on it, will reach out on the license upgrade when I get to the annotation stage.

**Comment by mrdvince** [comment]
Hello @theodu Here is the google docs link: https://docs.google.com/document/d/11YUTvCIR1Kq31UqD8MPllbM1K3G8xq0s/edit?usp=sharing&ouid=115520018587204261582&rtpof=true&sd=true

**Comment by theodu** [comment]
Thanks!, I will review it asap

**Comment by mrdvince** [comment]
@theodu Hello,
thanks, I have gone ahead and added the conclusion and a link to the GitHub repo for the reference code.

**Comment by theodu** [comment]
Hi @mrdvince Nice, You just missed a word in the conclusion, I let you add it.
@JustBrn This article is reviewed

**Comment by mrdvince** [comment]
@theodu I have seen the comment, thanks. Gone ahead and edited it.

**Comment by mrdvince** [comment]
hi @theodu how will I know if the article has been published?

**Comment by theodu** [comment]
Hi @mrdvince We will keep you in touch. I don't handle the second phase where we publish it but we will keep you in touch when we know the publication schedule date!

**Comment by JustBrn** [comment]
Hi @mrdvince I'll take care of publishing your article, and will let you know once done! It will be live next week.

**Comment by mrdvince** [comment]
Hi @JustBrn awesome thanks.

**Comment by JustBrn** [comment]
@mrdvince your article has been published! https://kili-technology.com/blog/aerial-object-using-yolov5-and-kili-technology
You can send your invoice now :)

**Comment by mrdvince** [comment]
Hello @JustBrn
Thanks, I've gone ahead and submitted the invoice.

**Comment by mrdvince** [comment]
@JustBrn [update] The invoice has been paid.
