### ISSUE TITLE
[Request New Content] Import OCR pre-annotations in Kili

### ISSUE THREAD

**Issue by theodu** [kili-technology/kili-blogger-program#7]
### My Request

Import OCR pre-annotations in Kili

### Community vote
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by souravsingh** [comment]
Hello @theodu I am interested in working on this topic.

**Comment by theodu** [comment]
Hi @souravsingh,
Happy to hear that you are interested!
Please provide a detailed outline of what you would like to write

**Comment by dhruvsheth-ai** [comment]
Hi, I'm interested to take this up!

### Outline
- High level introduction to OCR and potential applications
- Importance of quick and accurate OCR tools, and how Kili helps
- Brief overview on Kili's OCR segmentation and classification process
-  Going through the Dashboard and importing data samples
- Understanding demonstration of OCR pre-annotation through step-by-step process
- Efficiently pre-annotating the imported data.
-  Key Takeaways

**Comment by theodu** [comment]
Hi @souravsingh 
Sorry for the late reply, the end of the year period froze operations.
This outline sounds good! 

A little comment on bullet points 5 and 6 to give context: 
Currently, we don't have an OCR tool boosted with AI in Kili Technology and are working on it. 
Currently, on the platform, someone can draw a bounding box around a word or sentence and label it by typing what is written inside that box. see here for the documentation on OCR: https://cloud.kili-technology.com/docs/interfaces-text-pdf/image-transcription-ocr/#docsNav
Many people use the OCR tool in Kili but at the time, the only way to use AI boosted tool is to make a call to an external API and to import it to Kili as pre annotation. We already have a recipe on how to do it with Google Vision API here: https://github.com/kili-technology/kili-playground/blob/master/recipes/ocr_pre_annotations.ipynb. However, Google Vision API is not free. the best would be to do a tutorial on how to do this whole process with both google vision API and a free tool. 
Do you have access to google vision API? What API/tool were you thinking about to produce OCR predictions?

Best,

**Comment by theodu** [comment]
Hi, as we are working on an OCR tool at the time, I have to cancel this issue.
best,
Théo
