### ISSUE TITLE
Tutorial: Different Types of Data Augmentation

### ISSUE THREAD

**Issue by ErikValle** [kili-technology/kili-blogger-program#71]
### My resource

**Topic: Tutorial: Different Types of Data Augmentation**

**Outline: I would like to explain how different types of Data Augmentation techniques improve or worsen popular Machine Learning approaches such as VGG-16, YOLOv5, etc. I will use photometric transformations, geometric transformations, GAN, KNN, etc.**

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hi @ErikValle 
I am very sorry for the delay!
Unfortunately, data augmentation is not a target topic at the moment. 
But don't hesitate to propose other content!
