### ISSUE TITLE
[Article Proposal] Lip reading through visual cues - Without Audio cues or CNNs -

### ISSUE THREAD

**Issue by amrkh97** [kili-technology/kili-blogger-program#72]
### My resource

**Topic:**
Building a Lip reading application using Python3, Tensorflow & OpenCV through visual cues only as opposed to conventional Audio-visual cues datasets.

The tutorial will provide full code for the data prepration pipeline, data cleansing, data padding and the compele structure for the Deep learning models and training.
**Outline:**
1. Motivation for creating a lip-reading application
2. Choosing the dataset and how to download it
3. Data cleansing & Preparation
4. Building the DL model
5. Results, Fi dings and future improvements

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by amrkh97** [comment]
Hi @theodu , would love to hear your input on this article proposal and if there are any modification that you see that would fit better.

**Comment by theodu** [comment]
Hi @amrkh97 
Thank you for your article proposal!
Even if this article deals with dataset selection and cleaning, it is quite model-centric and I don't see what it would bring to the data-centric topic. How can you turn your article so that it brings something to the data-centric approach ?

Thank you!

**Comment by amrkh97** [comment]
Hi @theodu , Sorry for the late reply.

One way I can make it data-centric is by focusing on different techniques to handle images, whether it is for an OCR, a Lip reading app or if you are just playing around. how can we detect various types of images, contexts and objects.

**Comment by theodu** [comment]
Hi @amrkh97, also sorry for the late reply
We won't continue with this article because we recently published an article on image modeling and this one does not add a topic that we are interested into.
But do not hesitate to make another article proposal!
best,
