### ISSUE TITLE
[Article Proposal] Methods for Clinical Text Classification 

### ISSUE THREAD

**Issue by Renerd-max** [kili-technology/kili-blogger-program#74]
### My resource

**Topic:** Methods for Clinical Text Classification 

**Outline:**
**Introduction**

What is clinical text classification, its usefulness and how Kili can help?

**Various Methods of clinical Text classifications**

Will provide descriptions with examples.

**Understanding the Business Model.**
**Understanding available data**
**Data Preparation**
**Data modelling and evaluation**
**Deploying the model**

**Conclusion**

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by JustBrn** [comment]
@Renerd-max thanks for your submission! We'll take a look and get back to you.

**Comment by theodu** [comment]
hi @Renerd-max, We already published an article on text classification recently and we do not see any added value for that one.
thank you for this proposal!
