### ISSUE TITLE
[Article Proposal] Transformer is all you need.

### ISSUE THREAD

**Issue by inconnu11** [kili-technology/kili-blogger-program#76]
### My resource

**Topic:**
Transformer is all you need.

**Outline:**
What's Transformer?
What Matters in Transformer?
Transformer for CV
Transformer for NLP
Transformer for Multi-modal Tasks
Conclusion

### My content is

- [x] An Article

**Comment by JustBrn** [comment]
@inconnu11 thanks for your second submission! We'll review your proposal and get back to you.
