### ISSUE TITLE
[Article Proposal] How to transform a document image into a text sequence?

### ISSUE THREAD

**Issue by inconnu11** [kili-technology/kili-blogger-program#77]
### My resource

**Topic:**
How to transform a document image into a text sequence?

**Outline:**
Introduction
What's Document Layout Analysis?
What's Reading Order in Document?
Detecting and Recognizing texts (OCR) in Document Images
Detecting Page Objects in Document Images
Predicting Reading Order Relationships between Page Objecs
Applications
Key Task-ways

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by JustBrn** [comment]
@inconnu11 thanks for your submission! Let us take a look and get back to you.

**Comment by theodu** [comment]
Hi @inconnu11,
that seems to be a nice outline!
What data do you want to use and how do you intend to use Kili? We don't have an OCR model yet in the platform but we have an OCR annotation tool that you can use. 
And also, what do you call "Predicting Reading Order Relationships between Page Objects"?

**Comment by JustBrn** [comment]
Hi @inconnu11, any thoughts on Théo points above? Thanks!
