### ISSUE TITLE
[Request New Content] Guide to Human in the Loop Machine Learning

### ISSUE THREAD

**Issue by theodu** [kili-technology/kili-blogger-program#8]
### Community vote
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by FnSK4R17s** [comment]
🚀
## Summary
ML models are not perfect, their performance depends on the quality of data that they are trained on. Publically available datasets are more often than not, insufficient for training a model for production use cases. The dataset might not cover all the edge cases that might occur in real-world applications. In order to tackle this issue, we need to have a human in the loop who can find these edge cases and label the data required for the next round of model training.

## Outline
- Introduction
- Key Points to Remember
- Why do ML models need Fine-tuning
- What are edge cases and how to spot them
- Filtering data efficiently to find the required data
- Efficiently labeling the data
- Retraining the model
- Catastrophic forgetting
- Re-evaluating the model
- Final Summary

**Comment by theodu** [comment]
Hi @FnSK4R17s,
This outline seems wonderful!
You can begin to work on it

**Comment by FnSK4R17s** [comment]
> Hi @FnSK4R17s,
> This outline seems wonderful!
> You can begin to work on it
> 

Rodger that !

**Comment by FnSK4R17s** [comment]
Hi @theodu
Here is my first draft of the article.
https://docs.google.com/document/d/1nNluHrBsTWI7j9YudchiaWd8GU9Ch0Ue6OyW4Dp4A14/edit?usp=drivesdk

**Comment by FnSK4R17s** [comment]
Hi @theodu 
Here is my first draft of the article.

https://docs.google.com/document/d/1nNluHrBsTWI7j9YudchiaWd8GU9Ch0Ue6OyW4Dp4A14/edit?usp=drivesdk

**Comment by theodu** [comment]
Thank you @FnSK4R17s!
It will be reviewed asap!

**Comment by theodu** [comment]
hi @FnSK4R17s 
I went through your article. I find it wonderful. Very well written and it tackles exactly the topic.
I am still waiting for a second Kili member review and it will be ready for publishing.

**Comment by FnSK4R17s** [comment]
Thanks! Good to know.

**Comment by FnSK4R17s** [comment]
Hey, @theodu,

Thanks for the update. I need some help with these two things:

1. There seems to be an issue with the link that's provided in the FAQ section, I cannot open the form.
2. The FAQ section says that I need to mention the URL of the uploaded blogpost in the invoice. How do I go about doing that?

**Comment by theodu** [comment]
Hi @FnSK4R17s 
1. I changed the access right, it should work now
2. Indeed, I removed this question

I updated everything, you should now be able to submit it.

**Comment by FnSK4R17s** [comment]
@theodu Thanks for the prompt reply. I've submitted the invoice. 🚀

**Comment by theodu** [comment]
Great, I keep you in touch for the payment process

**Comment by theodu** [comment]
@FnSK4R17s In fact we wrote in the FAQ that the invoice should be submitted once the content is published.
I try to have an estimation of when we will publish it so you know when to submit again the form (I added the "URL of article" question back).
Sorry for this setback.
Best

**Comment by theodu** [comment]
Hi @FnSK4R17s 
Your article is scheduled to be published tomorrow morning at 9:00 GMT+1!
here is the link to the future article: https://kili-technology.com/blog/guide-to-human-in-the-loop-machine-learning/
You can submit the invoice form again with this link
Thank you for your wonderful involment!

**Comment by FnSK4R17s** [comment]
Hey @theodu
I have generated a new invoice with the article link. I'm excited to see my article published in your blog.
Thanks for the info !
Regards,
Shikhar

**Comment by FnSK4R17s** [comment]
Hey @theodu
I checked out the article on your blog. Just wanted to ask you if I will be credited as the author of the article or will it be a ghostwriter type of gig. Because I can see that the website shows that the article is written by you. Please clarify.
Regards,
Shikhar

**Comment by theodu** [comment]
Hi,
Indeed, as I copy-pasted the article and published it, it is published under my name.
This is not the expected behavior and it should be published under your name. I can't change it at the time since I don't have the edit right to do it, I ask them asap.
You are credited for the article and we will very soon make social media communication with the image that you created with your picture.
Regards,
Théo

**Comment by FnSK4R17s** [comment]
@theodu 
Thanks for the clarification Theo. I really appreciate that.
Regards,
Shikhar

**Comment by theodu** [comment]
@FnSK4R17s I sent you a mail to invite you to join our blog as a contributor, I need you to sign in to be able to put you as author

**Comment by FnSK4R17s** [comment]
Hey @theodu ,
I have joined using your invitation link. What do I need to do next?

Thanks,
Shikhar

**Comment by theodu** [comment]
Hi @FnSK4R17s 
That's it! 
For the next articles, you will have to get your article in shape in WordPress but I did it for this one.
I needed the invitation to change the author of the article

Best 
Théo

**Comment by theodu** [comment]
Hi @FnSK4R17s 
I didn't add the IBAN on the invoice but we also need it to send the money. Can you please send me a mail at theo.dullin@kili-technology.com with your IBAN? No need to resubmit the invoice.
You are the first one to have reached the article publication, so it requires us to adapt our workflow. I am sorry about the delay.
Regards,
Théo

**Comment by theodu** [comment]
Okay, then the limitation comes from our side. Our bank only accepts IBAN as necessary information to do a money transfer.

**Comment by FnSK4R17s** [comment]
Yeah, my country doesn't use IBAN. There should be a provision for that. You should probably check with your bank. Thanks.

**Comment by theodu** [comment]
ok, we'll have a deeper look!

**Comment by FnSK4R17s** [comment]
@theodu Payment Received 🎉

**Comment by theodu** [comment]
Very good!
The article is very good, congratz!
